logging:
  level:
    web: trace
    core: trace
spring:
  profiles:
    active: ${PROFILE}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  security:
    oauth2:
      client:
        registration:
          authentik:
            client-id: ${AUTHENTIK_CLIENT_ID}
            client-secret: ${AUTHENTIK_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/authentik"
        provider:
          authentik:
            back-channel-logout-url: ${AUTHENTIK_BACK_CHANNEL_LOGOUT_URL} # spring doesn't support back-channel logouts by default
            issuer-uri: ${AUTHENTIK_ISSUER_URL}
  cloud:
    gateway:
      set-status:
        original-status-header-name: Original-Status
      routes:
        - id: api
          uri: ${API_URI}
          order: 1
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: spa
          order: 10
          uri: ${FRONTEND_URI}
          predicates:
            - Path=/**
server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/local.p12
    key-store-password: asdf1234
    key-alias: local
  reactive:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: lax
        max-age: 30m
        path: "/"