spring:
  cloud:
    gateway:
      routes:
        - id: core-api
          uri: ${CORE_API_URI}
          order: 1
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: statements-api
          uri: ${STATEMENTS_API_URI}
          order: 2
          predicates:
            - Path=/api/statements/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: widgets-api
          uri: ${WIDGETS_API_URI}
          order: 3
          predicates:
            - Path=/api/widgets/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: spa
          order: 4
          uri: ${FRONTEND_URI}
          predicates:
            - Path=/**